### ISSUE TITLE
Startup scripts are broken in version quickstart 2.0.5 (docker)

### ISSUE THREAD

**Issue by tools-proservia** [zatosource/zato-build#26]
After buidling a new docker 2.0.5 docker image, here is what I got at startup :

>
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 691, in execute
    listing = set(os.listdir(self.component_dir))
OSError: [Errno 2] No such file or directory: '/opt/zato/load-balancer'
>
2015-06-17 13:33:47,492 DEBG 'zato-web-admin' stdout output:
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 691, in execute
    listing = set(os.listdir(self.component_dir))
OSError: [Errno 2] No such file or directory: '/opt/zato/web-admin'
>
2015-06-17 13:33:47,494 DEBG 'zato-server1' stdout output:
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 691, in execute
    listing = set(os.listdir(self.component_dir))
OSError: [Errno 2] No such file or directory: '/opt/zato/server1'
>
2015-06-17 13:33:47,521 DEBG 'zato-server2' stdout output:
Traceback (most recent call last):
  File "/opt/zato/2.0.5/bin/zato", line 181, in <module>
    sys.exit(zato.cli.zato_command.main())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/zato_command.py", line 262, in main
    return run_command(get_parser().parse_args())
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 265, in run_command
    command_class[args.command](args).run(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 481, in run
    return_code = self.execute(args)
  File "/opt/zato/2.0.5/zato-cli/src/zato/cli/__init__.py", line 691, in execute
    listing = set(os.listdir(self.component_dir))
OSError: [Errno 2] No such file or directory: '/opt/zato/server2'

Startup scripts in /opt/zato/ were modified since commit dc03b2ede8a4e67c3da8dd815d5f57171028c013. 

After deleting the following lines in all /opt/zato/zato_start_* scripts, my zato instance can start successfully :

```shell
cd /opt/zato
ZATO_VERSION=`ls | sort -n | tail -1`
```

**Comment by rafal-k** [comment]
Thank you for reporting this so quickly. Could you try to build a new 2.0.5 Docker image?

**Comment by tools-proservia** [comment]
Problem solved, startup is OK with my new image.
Cheers !
