### ISSUE TITLE
Invalid Credentials on /zato/jwt/log-in zato3.1

### ISSUE THREAD

**Issue by LordShion** [zatosource/zato-build#74]
Zato 3.1+rev.f40ada359-py3.6.8

on a fresh docker install with quickstart create
I defined a JWT in the web admin.
as follows
Name: FilipeToken
username: filipesisi
changed password to :  #zato2021

when curling for a token, returns invalid credentials,  what I am doing wrong
```
curl -X POST http://localhost:11223/zato/jwt/log-in -d '{"username":"filipesisi", "password":"#zato2021"}'
{"zato_env": {"result": "ZATO_ERROR", "cid": "d7e2a6eed760f1133446dc9a", "details": "Invalid credentials"}}
```
copy of traceback
```
zato31_1    | 2021-11-23 23:31:47,190 - ERROR - 363:DummyThread-43 - zato.server.connection.http_soap.channel:0 - Caught an exception, cid:`d7e2a6eed760f1133446dc9a`, status_code:`HTTPStatus.UNAUTHORIZED`, `Traceback (most recent call last):
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/security/jwt.py", line 247, in handle
zato31_1    |     token, self.request.input.totp_code)
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/sso.py", line 53, in on_external_auth
zato31_1    |     auth_id_link_map = self.server.sso_api.user.auth_id_link_map['zato.{}'.format(sec_type)] # type: dict
zato31_1    | AttributeError: 'NoneType' object has no attribute 'user'
zato31_1    | 
zato31_1    | During handling of the above exception, another exception occurred:
zato31_1    | 
zato31_1    | Traceback (most recent call last):
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 355, in dispatch
zato31_1    |     payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 625, in handle
zato31_1    |     params_priority=channel_item.params_pri)
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 712, in update_handle
zato31_1    |     raise e if isinstance(e, Exception) else Exception(e)
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 660, in update_handle
zato31_1    |     self._invoke(service, channel)
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/__init__.py", line 547, in _invoke
zato31_1    |     service.handle()
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/security/jwt.py", line 257, in handle
zato31_1    |     self._raise_unathorized()
zato31_1    |   File "/opt/zato/3.1.0/code/zato-server/src/zato/server/service/internal/security/jwt.py", line 229, in _raise_unathorized
zato31_1    |     raise Unauthorized(self.cid, 'Invalid credentials', 'jwt')
zato31_1    | zato.common.exception.Unauthorized: <Unauthorized at 0x7f196a8dc828 cid:`d7e2a6eed760f1133446dc9a`, msg:`Invalid credentials`>

```

**Comment by dsuch** [comment]
Hello @LordShion,

support for version 3.1 is available only to commercial clients.

For details, please contact me on dsuch@zato.io using your business email address.

Regards.
