### ISSUE TITLE
Required element `id` missing in `{} on JWT creation web-admin zato3.2

### ISSUE THREAD

**Issue by LordShion** [zatosource/zato-build#75]
Zato 3.2+rev.45ab14fb-py3.6.9-ubuntu.18.04-bionic

on a fresh docker install 3.2 with quickstart create
I Tried to define a JWT in the web admin
as follows
Name: FilipeToken
username: filipesisi
TTL: 3600
Am I missing something
best regards
Filipe

`Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/web/views/__init__.py", line 582, in __call__
    response = self.req.zato.client.invoke(self.service_name, self.input_dict)
  File "/opt/zato/3.2.0/code/zato-web-admin/src/zato/admin/middleware.py", line 92, in invoke
    raise Exception('CID: {}\nDetails: {}'.format(json_data.get('cid'), json_data.get('details')))
Exception: CID: 92ef9bf540fccb4a2f31e472
Details: Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 774, in update_handle
    response = set_response_func(service, data_format=data_format, transport=transport, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 589, in set_response_data
    response = response.getvalue(serialize=kwargs.get('serialize'))
  File "src/zato/cy/reqresp/payload.py", line 201, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/reqresp/payload.py", line 229, in zato.cy.reqresp.payload.SimpleIOPayload.getvalue
  File "src/zato/cy/simpleio.py", line 2198, in zato.simpleio.CySimpleIO.get_output
  File "src/zato/cy/simpleio.py", line 2151, in zato.simpleio.CySimpleIO._get_output_json
  File "src/zato/cy/simpleio.py", line 2131, in zato.simpleio.CySimpleIO._convert_to_dicts
  File "src/zato/cy/simpleio.py", line 2052, in _yield_data_dicts
zato.simpleio.SerialisationError: Required element `id` missing in `{}` (<class 'zato.server.service.internal.security.jwt.Create'>)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 382, in dispatch
    payload, worker_store, self.simple_io_config, post_data, path_info, soap_action)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/connection/http_soap/channel.py", line 689, in handle
    params_priority=channel_item.params_pri)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 804, in update_handle
    raise e if isinstance(e, Exception) else Exception(e)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 746, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 627, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/service.py", line 482, in handle
    serialize=True)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 905, in invoke
    return self.invoke_by_impl_name(self.server.service_store.name_to_impl_name[name], *args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 883, in invoke_by_impl_name
    return self.update_handle(*invoke_args, **kwargs)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 799, in update_handle
    raise Exception(exc_formatted)
Exception: Traceback (most recent call last):
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 746, in update_handle
    self._invoke(service, channel)
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/__init__.py", line 627, in _invoke
    service.handle()
  File "/opt/zato/3.2.0/code/zato-server/src/zato/server/service/internal/security/jwt.py", line 98, in handle
    set_instance_opaque_attrs(item, input)
  File "/opt/zato/3.2.0/code/zato-common/src/zato/common/util/sql.py", line 268, in set_instance_opaque_attrs
    setattr(instance, GENERIC.ATTR_NAME, dumps(instance_opaque_attrs))
TypeError: reject_bytes is on and 'lz8FR_xTwCHWO_sISRCRztfCBzTNoAjc6-RsT4N90uw=' is bytes`

**Comment by dsuch** [comment]
Thank you, this is corrected and a new image is available. Please create a new container.

https://zato.io/docs/admin/guide/install/docker.html
